# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\310098157\Documents\GitHub\PythonProject\VayaSiteTool\VayaMfgMainWin.ui'
#
# Created: Fri Dec 19 12:44:51 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(890, 589)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(890, 589))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../Pictures/CK.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ConnectDeviceButton = QtGui.QPushButton(self.centralWidget)
        self.ConnectDeviceButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConnectDeviceButton.setFont(font)
        self.ConnectDeviceButton.setObjectName(_fromUtf8("ConnectDeviceButton"))
        self.label_Device_Status = QtGui.QLabel(self.centralWidget)
        self.label_Device_Status.setGeometry(QtCore.QRect(640, 11, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Device_Status.setFont(font)
        self.label_Device_Status.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_Device_Status.setObjectName(_fromUtf8("label_Device_Status"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 871, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.frame_2 = QtGui.QFrame(self.configuration)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 851, 401))
        self.frame_2.setStyleSheet(_fromUtf8(""))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pushButton_SelectPP = QtGui.QPushButton(self.frame_2)
        self.pushButton_SelectPP.setGeometry(QtCore.QRect(350, 190, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SelectPP.setFont(font)
        self.pushButton_SelectPP.setObjectName(_fromUtf8("pushButton_SelectPP"))
        self.pushButton_SetPara = QtGui.QPushButton(self.frame_2)
        self.pushButton_SetPara.setGeometry(QtCore.QRect(10, 320, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_SetPara.setFont(font)
        self.pushButton_SetPara.setObjectName(_fromUtf8("pushButton_SetPara"))
        self.pushButton_GetPara = QtGui.QPushButton(self.frame_2)
        self.pushButton_GetPara.setGeometry(QtCore.QRect(10, 110, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_GetPara.setFont(font)
        self.pushButton_GetPara.setObjectName(_fromUtf8("pushButton_GetPara"))
        self.comboBox_ModelList = QtGui.QComboBox(self.frame_2)
        self.comboBox_ModelList.setGeometry(QtCore.QRect(160, 270, 371, 31))
        self.comboBox_ModelList.setObjectName(_fromUtf8("comboBox_ModelList"))
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 270, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(350, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_foot = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_foot.setEnabled(True)
        self.lineEdit_foot.setGeometry(QtCore.QRect(490, 230, 41, 31))
        self.lineEdit_foot.setText(_fromUtf8(""))
        self.lineEdit_foot.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_foot.setReadOnly(True)
        self.lineEdit_foot.setObjectName(_fromUtf8("lineEdit_foot"))
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(10, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_FixtureModel = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_FixtureModel.setEnabled(True)
        self.lineEdit_FixtureModel.setGeometry(QtCore.QRect(160, 230, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_FixtureModel.setFont(font)
        self.lineEdit_FixtureModel.setText(_fromUtf8(""))
        self.lineEdit_FixtureModel.setReadOnly(True)
        self.lineEdit_FixtureModel.setObjectName(_fromUtf8("lineEdit_FixtureModel"))
        self.Config_PP = QtGui.QLabel(self.frame_2)
        self.Config_PP.setGeometry(QtCore.QRect(540, 190, 300, 200))
        self.Config_PP.setStyleSheet(_fromUtf8("background-color: rgb(216, 216, 216);"))
        self.Config_PP.setFrameShape(QtGui.QFrame.Box)
        self.Config_PP.setAlignment(QtCore.Qt.AlignCenter)
        self.Config_PP.setObjectName(_fromUtf8("Config_PP"))
        self.label_37 = QtGui.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 0);"))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.lineEdit_ProgramUID = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_ProgramUID.setGeometry(QtCore.QRect(190, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_ProgramUID.setFont(font)
        self.lineEdit_ProgramUID.setObjectName(_fromUtf8("lineEdit_ProgramUID"))
        self.lineEdit_PPname = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_PPname.setGeometry(QtCore.QRect(160, 190, 181, 31))
        self.lineEdit_PPname.setReadOnly(True)
        self.lineEdit_PPname.setObjectName(_fromUtf8("lineEdit_PPname"))
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(10, 190, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_5068 = QtGui.QLabel(self.frame_2)
        self.label_5068.setGeometry(QtCore.QRect(125, 30, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5068.setFont(font)
        self.label_5068.setObjectName(_fromUtf8("label_5068"))
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(10, 170, 831, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(349, 10, 491, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(300, 100, 91, 21))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(300, 40, 91, 21))
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(300, 70, 91, 21))
        self.label_7.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(300, 130, 91, 21))
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Readback_UID = QtGui.QLabel(self.frame)
        self.Readback_UID.setGeometry(QtCore.QRect(100, 40, 191, 21))
        self.Readback_UID.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_UID.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_UID.setObjectName(_fromUtf8("Readback_UID"))
        self.Readback_DMX = QtGui.QLabel(self.frame)
        self.Readback_DMX.setGeometry(QtCore.QRect(100, 70, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_DMX.setFont(font)
        self.Readback_DMX.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_DMX.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_DMX.setObjectName(_fromUtf8("Readback_DMX"))
        self.Readback_Model = QtGui.QLabel(self.frame)
        self.Readback_Model.setGeometry(QtCore.QRect(100, 100, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_Model.setFont(font)
        self.Readback_Model.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_Model.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_Model.setObjectName(_fromUtf8("Readback_Model"))
        self.Readback_MID = QtGui.QLabel(self.frame)
        self.Readback_MID.setGeometry(QtCore.QRect(100, 130, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_MID.setFont(font)
        self.Readback_MID.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_MID.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_MID.setObjectName(_fromUtf8("Readback_MID"))
        self.Readback_Footprint = QtGui.QLabel(self.frame)
        self.Readback_Footprint.setGeometry(QtCore.QRect(390, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_Footprint.setFont(font)
        self.Readback_Footprint.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_Footprint.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_Footprint.setObjectName(_fromUtf8("Readback_Footprint"))
        self.Readback_FWversion = QtGui.QLabel(self.frame)
        self.Readback_FWversion.setGeometry(QtCore.QRect(390, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_FWversion.setFont(font)
        self.Readback_FWversion.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_FWversion.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_FWversion.setObjectName(_fromUtf8("Readback_FWversion"))
        self.Readback_RDMversion = QtGui.QLabel(self.frame)
        self.Readback_RDMversion.setGeometry(QtCore.QRect(390, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_RDMversion.setFont(font)
        self.Readback_RDMversion.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_RDMversion.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_RDMversion.setObjectName(_fromUtf8("Readback_RDMversion"))
        self.Readback_Device = QtGui.QLabel(self.frame)
        self.Readback_Device.setGeometry(QtCore.QRect(390, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Readback_Device.setFont(font)
        self.Readback_Device.setStyleSheet(_fromUtf8("background-color: rgb(180, 180, 180);\n"
""))
        self.Readback_Device.setAlignment(QtCore.Qt.AlignCenter)
        self.Readback_Device.setObjectName(_fromUtf8("Readback_Device"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 91, 21))
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(200, 200, 200);"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_18 = QtGui.QLabel(self.configuration)
        self.label_18.setGeometry(QtCore.QRect(0, 410, 871, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);\n"
"color: rgb(150, 150, 150);"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget.addTab(self.configuration, _fromUtf8(""))
        self.channeltest = QtGui.QWidget()
        self.channeltest.setObjectName(_fromUtf8("channeltest"))
        self.label_35 = QtGui.QLabel(self.channeltest)
        self.label_35.setGeometry(QtCore.QRect(20, 220, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalSlider_value = QtGui.QSlider(self.channeltest)
        self.horizontalSlider_value.setGeometry(QtCore.QRect(70, 220, 160, 21))
        self.horizontalSlider_value.setMaximum(255)
        self.horizontalSlider_value.setProperty("value", 255)
        self.horizontalSlider_value.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_value.setObjectName(_fromUtf8("horizontalSlider_value"))
        self.pushButton_testchannelAllOn = QtGui.QPushButton(self.channeltest)
        self.pushButton_testchannelAllOn.setGeometry(QtCore.QRect(644, 210, 131, 31))
        self.pushButton_testchannelAllOn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_testchannelAllOn.setDefault(False)
        self.pushButton_testchannelAllOn.setFlat(False)
        self.pushButton_testchannelAllOn.setObjectName(_fromUtf8("pushButton_testchannelAllOn"))
        self.tableWidget_channeltest = QtGui.QTableWidget(self.channeltest)
        self.tableWidget_channeltest.setEnabled(True)
        self.tableWidget_channeltest.setGeometry(QtCore.QRect(10, 20, 782, 181))
        self.tableWidget_channeltest.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_channeltest.setStyleSheet(_fromUtf8(""))
        self.tableWidget_channeltest.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_channeltest.setLineWidth(1)
        self.tableWidget_channeltest.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_channeltest.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_channeltest.setDragDropOverwriteMode(False)
        self.tableWidget_channeltest.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_channeltest.setShowGrid(True)
        self.tableWidget_channeltest.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_channeltest.setRowCount(32)
        self.tableWidget_channeltest.setColumnCount(16)
        self.tableWidget_channeltest.setObjectName(_fromUtf8("tableWidget_channeltest"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_channeltest.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_channeltest.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_channeltest.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(31, 14, item)
        self.tableWidget_channeltest.horizontalHeader().setVisible(False)
        self.tableWidget_channeltest.horizontalHeader().setDefaultSectionSize(47)
        self.tableWidget_channeltest.horizontalHeader().setHighlightSections(True)
        self.tableWidget_channeltest.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_channeltest.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_channeltest.verticalHeader().setVisible(False)
        self.spinBox_2 = QtGui.QSpinBox(self.channeltest)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QtCore.QRect(240, 220, 42, 22))
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setProperty("value", 255)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.pushButton_testchannelAllOff = QtGui.QPushButton(self.channeltest)
        self.pushButton_testchannelAllOff.setGeometry(QtCore.QRect(500, 210, 131, 31))
        self.pushButton_testchannelAllOff.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_testchannelAllOff.setAutoDefault(False)
        self.pushButton_testchannelAllOff.setDefault(False)
        self.pushButton_testchannelAllOff.setFlat(False)
        self.pushButton_testchannelAllOff.setObjectName(_fromUtf8("pushButton_testchannelAllOff"))
        self.tabWidget.addTab(self.channeltest, _fromUtf8(""))
        self.DisconnectDeviceButton = QtGui.QPushButton(self.centralWidget)
        self.DisconnectDeviceButton.setEnabled(False)
        self.DisconnectDeviceButton.setGeometry(QtCore.QRect(140, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DisconnectDeviceButton.setFont(font)
        self.DisconnectDeviceButton.setObjectName(_fromUtf8("DisconnectDeviceButton"))
        self.label_Device_Status_2 = QtGui.QLabel(self.centralWidget)
        self.label_Device_Status_2.setGeometry(QtCore.QRect(700, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Device_Status_2.setFont(font)
        self.label_Device_Status_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label_Device_Status_2.setFrameShape(QtGui.QFrame.Box)
        self.label_Device_Status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Device_Status_2.setObjectName(_fromUtf8("label_Device_Status_2"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(7, 40, 881, 20))
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_34 = QtGui.QLabel(self.centralWidget)
        self.label_34.setGeometry(QtCore.QRect(580, 550, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.frame_7 = QtGui.QFrame(self.centralWidget)
        self.frame_7.setGeometry(QtCore.QRect(540, 550, 31, 31))
        self.frame_7.setStyleSheet(_fromUtf8("image: url(:/logo/CK.ico);"))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_SJP = QtGui.QLabel(self.centralWidget)
        self.label_SJP.setGeometry(QtCore.QRect(600, 10, 31, 31))
        self.label_SJP.setText(_fromUtf8(""))
        self.label_SJP.setObjectName(_fromUtf8("label_SJP"))
        self.label_version = QtGui.QLabel(self.centralWidget)
        self.label_version.setGeometry(QtCore.QRect(10, 550, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_version.setFont(font)
        self.label_version.setObjectName(_fromUtf8("label_version"))
        self.lineEdit_Today = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_Today.setEnabled(True)
        self.lineEdit_Today.setGeometry(QtCore.QRect(100, 550, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(11)
        self.lineEdit_Today.setFont(font)
        self.lineEdit_Today.setText(_fromUtf8(""))
        self.lineEdit_Today.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Today.setReadOnly(True)
        self.lineEdit_Today.setObjectName(_fromUtf8("lineEdit_Today"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Vaya on Site", None))
        self.ConnectDeviceButton.setText(_translate("MainWindow", "Connect", None))
        self.label_Device_Status.setText(_translate("MainWindow", " Status:", None))
        self.pushButton_SelectPP.setText(_translate("MainWindow", "Select Profile", None))
        self.pushButton_SetPara.setText(_translate("MainWindow", "Set Parameters", None))
        self.pushButton_GetPara.setText(_translate("MainWindow", "Read Parameters", None))
        self.label_19.setText(_translate("MainWindow", "Model Description", None))
        self.label_20.setText(_translate("MainWindow", "DMX Footprint", None))
        self.label_22.setText(_translate("MainWindow", "Fixture Model", None))
        self.Config_PP.setText(_translate("MainWindow", "Fixture Image", None))
        self.label_37.setText(_translate("MainWindow", "UID/SN", None))
        self.label_27.setText(_translate("MainWindow", "File Name", None))
        self.label_5068.setText(_translate("MainWindow", "5068:", None))
        self.label.setText(_translate("MainWindow", "UID", None))
        self.label_2.setText(_translate("MainWindow", "DMX Address", None))
        self.label_4.setText(_translate("MainWindow", "Model Description", None))
        self.label_5.setText(_translate("MainWindow", "RDM Version", None))
        self.label_6.setText(_translate("MainWindow", "Footprint", None))
        self.label_7.setText(_translate("MainWindow", "Firmware Version", None))
        self.label_9.setText(_translate("MainWindow", "Device Label", None))
        self.Readback_UID.setText(_translate("MainWindow", "-", None))
        self.Readback_DMX.setText(_translate("MainWindow", "-", None))
        self.Readback_Model.setText(_translate("MainWindow", "-", None))
        self.Readback_MID.setText(_translate("MainWindow", "-", None))
        self.Readback_Footprint.setText(_translate("MainWindow", "-", None))
        self.Readback_FWversion.setText(_translate("MainWindow", "-", None))
        self.Readback_RDMversion.setText(_translate("MainWindow", "-", None))
        self.Readback_Device.setText(_translate("MainWindow", "-", None))
        self.label_17.setText(_translate("MainWindow", "Readback from the Fixture", None))
        self.label_8.setText(_translate("MainWindow", "Manufacturer ID", None))
        self.label_18.setText(_translate("MainWindow", "Set The Model Decription and DMX Footprint to The Target UID", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration), _translate("MainWindow", "Configuration", None))
        self.label_35.setText(_translate("MainWindow", "Value", None))
        self.pushButton_testchannelAllOn.setText(_translate("MainWindow", "ALL ON", None))
        self.tableWidget_channeltest.setSortingEnabled(False)
        item = self.tableWidget_channeltest.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "14", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "15", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "16", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "17", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "18", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "20", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "14", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "16", None))
        __sortingEnabled = self.tableWidget_channeltest.isSortingEnabled()
        self.tableWidget_channeltest.setSortingEnabled(False)
        item = self.tableWidget_channeltest.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_channeltest.item(0, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_channeltest.item(0, 2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_channeltest.item(0, 3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_channeltest.item(0, 4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_channeltest.item(0, 5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_channeltest.item(0, 6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_channeltest.item(0, 7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_channeltest.item(0, 8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget_channeltest.item(0, 9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_channeltest.item(0, 10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget_channeltest.item(0, 11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget_channeltest.item(0, 12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget_channeltest.item(0, 13)
        item.setText(_translate("MainWindow", "14", None))
        item = self.tableWidget_channeltest.item(0, 14)
        item.setText(_translate("MainWindow", "15", None))
        item = self.tableWidget_channeltest.item(0, 15)
        item.setText(_translate("MainWindow", "16", None))
        item = self.tableWidget_channeltest.item(31, 14)
        item.setText(_translate("MainWindow", "512", None))
        self.tableWidget_channeltest.setSortingEnabled(__sortingEnabled)
        self.pushButton_testchannelAllOff.setText(_translate("MainWindow", "ALL OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.channeltest), _translate("MainWindow", "Channel Test", None))
        self.DisconnectDeviceButton.setText(_translate("MainWindow", "Disconnect", None))
        self.label_Device_Status_2.setText(_translate("MainWindow", "No Smart Jack Pro Connected", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4891d9;\">Philips Solid State Lighting Solutions</span></p></body></html>", None))
        self.label_version.setText(_translate("MainWindow", "Ver.: V1.0.3", None))

import gamut_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

