# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\310098157\Dropbox\Works@PCK\Engineering\Working Directory\Software Project\Python Project\VayaManufacturingToolV1\VayaMfgMainWin.ui'
#
# Created: Thu Jun 26 14:01:13 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(820, 715)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(820, 715))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../Pictures/CK.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ConnectDeviceButton = QtGui.QPushButton(self.centralWidget)
        self.ConnectDeviceButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConnectDeviceButton.setFont(font)
        self.ConnectDeviceButton.setObjectName(_fromUtf8("ConnectDeviceButton"))
        self.label_Device_Status = QtGui.QLabel(self.centralWidget)
        self.label_Device_Status.setGeometry(QtCore.QRect(570, 11, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Device_Status.setFont(font)
        self.label_Device_Status.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_Device_Status.setObjectName(_fromUtf8("label_Device_Status"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 801, 601))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.frame_3 = QtGui.QFrame(self.configuration)
        self.frame_3.setGeometry(QtCore.QRect(10, 410, 771, 141))
        self.frame_3.setStyleSheet(_fromUtf8(""))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton_CH1 = QtGui.QPushButton(self.frame_3)
        self.pushButton_CH1.setGeometry(QtCore.QRect(10, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_CH1.setFont(font)
        self.pushButton_CH1.setObjectName(_fromUtf8("pushButton_CH1"))
        self.pushButton_CH2 = QtGui.QPushButton(self.frame_3)
        self.pushButton_CH2.setGeometry(QtCore.QRect(140, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_CH2.setFont(font)
        self.pushButton_CH2.setObjectName(_fromUtf8("pushButton_CH2"))
        self.pushButton_CH3 = QtGui.QPushButton(self.frame_3)
        self.pushButton_CH3.setGeometry(QtCore.QRect(270, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_CH3.setFont(font)
        self.pushButton_CH3.setObjectName(_fromUtf8("pushButton_CH3"))
        self.pushButton_CH4 = QtGui.QPushButton(self.frame_3)
        self.pushButton_CH4.setGeometry(QtCore.QRect(10, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_CH4.setFont(font)
        self.pushButton_CH4.setObjectName(_fromUtf8("pushButton_CH4"))
        self.pushButton_ALLON = QtGui.QPushButton(self.frame_3)
        self.pushButton_ALLON.setGeometry(QtCore.QRect(140, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ALLON.setFont(font)
        self.pushButton_ALLON.setObjectName(_fromUtf8("pushButton_ALLON"))
        self.pushButton_ALLOFF = QtGui.QPushButton(self.frame_3)
        self.pushButton_ALLOFF.setGeometry(QtCore.QRect(270, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ALLOFF.setFont(font)
        self.pushButton_ALLOFF.setObjectName(_fromUtf8("pushButton_ALLOFF"))
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(410, 20, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(420, 66, 131, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(420, 90, 111, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(410, 40, 351, 91))
        self.frame_4.setStyleSheet(_fromUtf8(""))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.frame_4)
        self.lcdNumber_2.setGeometry(QtCore.QRect(130, 50, 64, 31))
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.pushButton_test = QtGui.QPushButton(self.frame_4)
        self.pushButton_test.setGeometry(QtCore.QRect(230, 20, 75, 23))
        self.pushButton_test.setObjectName(_fromUtf8("pushButton_test"))
        self.pushButton_test_2 = QtGui.QPushButton(self.frame_4)
        self.pushButton_test_2.setGeometry(QtCore.QRect(230, 50, 75, 23))
        self.pushButton_test_2.setObjectName(_fromUtf8("pushButton_test_2"))
        self.lcdNumber = QtGui.QLCDNumber(self.frame_3)
        self.lcdNumber.setGeometry(QtCore.QRect(540, 60, 64, 31))
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.label_26 = QtGui.QLabel(self.configuration)
        self.label_26.setGeometry(QtCore.QRect(35, 390, 746, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("background-color: rgb(130, 200, 255);"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_18 = QtGui.QLabel(self.configuration)
        self.label_18.setGeometry(QtCore.QRect(35, 140, 746, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("background-color: rgb(130, 200, 255);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.frame = QtGui.QFrame(self.configuration)
        self.frame.setGeometry(QtCore.QRect(10, 30, 771, 101))
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(330, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_3 = QtGui.QLineEdit(self.frame)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(480, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_UID = QtGui.QLineEdit(self.frame)
        self.lineEdit_UID.setGeometry(QtCore.QRect(280, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_UID.setFont(font)
        self.lineEdit_UID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_UID.setObjectName(_fromUtf8("lineEdit_UID"))
        self.GenerateUID_2 = QtGui.QPushButton(self.frame)
        self.GenerateUID_2.setGeometry(QtCore.QRect(420, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GenerateUID_2.setFont(font)
        self.GenerateUID_2.setObjectName(_fromUtf8("GenerateUID_2"))
        self.comboBox_CMList = QtGui.QComboBox(self.frame)
        self.comboBox_CMList.setGeometry(QtCore.QRect(80, 60, 91, 31))
        self.comboBox_CMList.setObjectName(_fromUtf8("comboBox_CMList"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(250, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.frame)
        self.textBrowser_2.setEnabled(False)
        self.textBrowser_2.setGeometry(QtCore.QRect(540, 5, 221, 91))
        self.textBrowser_2.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_2.setLineWidth(1)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.label_13 = QtGui.QLabel(self.configuration)
        self.label_13.setGeometry(QtCore.QRect(35, 10, 746, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(130, 200, 255);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame_2 = QtGui.QFrame(self.configuration)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(10, 160, 771, 221))
        self.frame_2.setStyleSheet(_fromUtf8(""))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit_Today = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_Today.setEnabled(True)
        self.lineEdit_Today.setGeometry(QtCore.QRect(105, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(11)
        self.lineEdit_Today.setFont(font)
        self.lineEdit_Today.setText(_fromUtf8(""))
        self.lineEdit_Today.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Today.setReadOnly(True)
        self.lineEdit_Today.setObjectName(_fromUtf8("lineEdit_Today"))
        self.pushButton_SelectPP = QtGui.QPushButton(self.frame_2)
        self.pushButton_SelectPP.setGeometry(QtCore.QRect(330, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SelectPP.setFont(font)
        self.pushButton_SelectPP.setObjectName(_fromUtf8("pushButton_SelectPP"))
        self.pushButton_SetPara = QtGui.QPushButton(self.frame_2)
        self.pushButton_SetPara.setGeometry(QtCore.QRect(20, 170, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SetPara.setFont(font)
        self.pushButton_SetPara.setObjectName(_fromUtf8("pushButton_SetPara"))
        self.pushButton_GetPara = QtGui.QPushButton(self.frame_2)
        self.pushButton_GetPara.setGeometry(QtCore.QRect(240, 170, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_GetPara.setFont(font)
        self.pushButton_GetPara.setObjectName(_fromUtf8("pushButton_GetPara"))
        self.comboBox_ModelList = QtGui.QComboBox(self.frame_2)
        self.comboBox_ModelList.setGeometry(QtCore.QRect(115, 50, 201, 31))
        self.comboBox_ModelList.setObjectName(_fromUtf8("comboBox_ModelList"))
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(300, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(240, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.spinBox = QtGui.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(400, 90, 51, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(511)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.lineEdit_foot = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_foot.setEnabled(True)
        self.lineEdit_foot.setGeometry(QtCore.QRect(400, 130, 51, 31))
        self.lineEdit_foot.setText(_fromUtf8(""))
        self.lineEdit_foot.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_foot.setReadOnly(True)
        self.lineEdit_foot.setObjectName(_fromUtf8("lineEdit_foot"))
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(10, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_FixtureModel = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_FixtureModel.setEnabled(True)
        self.lineEdit_FixtureModel.setGeometry(QtCore.QRect(90, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_FixtureModel.setFont(font)
        self.lineEdit_FixtureModel.setText(_fromUtf8(""))
        self.lineEdit_FixtureModel.setReadOnly(True)
        self.lineEdit_FixtureModel.setObjectName(_fromUtf8("lineEdit_FixtureModel"))
        self.Config_PP = QtGui.QLabel(self.frame_2)
        self.Config_PP.setGeometry(QtCore.QRect(460, 10, 300, 200))
        self.Config_PP.setStyleSheet(_fromUtf8("background-color: rgb(216, 216, 216);"))
        self.Config_PP.setFrameShape(QtGui.QFrame.Box)
        self.Config_PP.setAlignment(QtCore.Qt.AlignCenter)
        self.Config_PP.setObjectName(_fromUtf8("Config_PP"))
        self.label_37 = QtGui.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(10, 90, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.lineEdit_ProgramUID = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_ProgramUID.setGeometry(QtCore.QRect(40, 90, 191, 31))
        self.lineEdit_ProgramUID.setObjectName(_fromUtf8("lineEdit_ProgramUID"))
        self.lineEdit_PPname = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_PPname.setGeometry(QtCore.QRect(290, 10, 161, 31))
        self.lineEdit_PPname.setReadOnly(True)
        self.lineEdit_PPname.setObjectName(_fromUtf8("lineEdit_PPname"))
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(230, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label = QtGui.QLabel(self.configuration)
        self.label.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(0, 120, 176);"))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.configuration)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 21, 21))
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 120, 176);"))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.configuration)
        self.label_4.setGeometry(QtCore.QRect(10, 390, 21, 21))
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 120, 176);"))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.configuration, _fromUtf8(""))
        self.addressing = QtGui.QWidget()
        self.addressing.setObjectName(_fromUtf8("addressing"))
        self.tableWidget_DiscoverFixtures = QtGui.QTableWidget(self.addressing)
        self.tableWidget_DiscoverFixtures.setGeometry(QtCore.QRect(10, 10, 781, 271))
        self.tableWidget_DiscoverFixtures.setStyleSheet(_fromUtf8(""))
        self.tableWidget_DiscoverFixtures.setObjectName(_fromUtf8("tableWidget_DiscoverFixtures"))
        self.tableWidget_DiscoverFixtures.setColumnCount(8)
        self.tableWidget_DiscoverFixtures.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_DiscoverFixtures.setHorizontalHeaderItem(7, item)
        self.pushButton_Discover = QtGui.QPushButton(self.addressing)
        self.pushButton_Discover.setGeometry(QtCore.QRect(370, 520, 131, 41))
        self.pushButton_Discover.setObjectName(_fromUtf8("pushButton_Discover"))
        self.tabWidget_2 = QtGui.QTabWidget(self.addressing)
        self.tabWidget_2.setGeometry(QtCore.QRect(370, 310, 411, 201))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(30, 10, 141, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_DMXAddr = QtGui.QLineEdit(self.tab)
        self.lineEdit_DMXAddr.setEnabled(True)
        self.lineEdit_DMXAddr.setGeometry(QtCore.QRect(30, 30, 181, 31))
        self.lineEdit_DMXAddr.setObjectName(_fromUtf8("lineEdit_DMXAddr"))
        self.Button_DMXSet = QtGui.QPushButton(self.tab)
        self.Button_DMXSet.setEnabled(True)
        self.Button_DMXSet.setGeometry(QtCore.QRect(240, 30, 101, 31))
        self.Button_DMXSet.setObjectName(_fromUtf8("Button_DMXSet"))
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(30, 110, 141, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_DeviceLabel = QtGui.QLineEdit(self.tab)
        self.lineEdit_DeviceLabel.setEnabled(True)
        self.lineEdit_DeviceLabel.setGeometry(QtCore.QRect(30, 130, 181, 31))
        self.lineEdit_DeviceLabel.setObjectName(_fromUtf8("lineEdit_DeviceLabel"))
        self.Button_LabelSet = QtGui.QPushButton(self.tab)
        self.Button_LabelSet.setEnabled(True)
        self.Button_LabelSet.setGeometry(QtCore.QRect(240, 130, 101, 31))
        self.Button_LabelSet.setObjectName(_fromUtf8("Button_LabelSet"))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(30, 60, 141, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.lineEdit_LightNo = QtGui.QLineEdit(self.tab)
        self.lineEdit_LightNo.setEnabled(True)
        self.lineEdit_LightNo.setGeometry(QtCore.QRect(30, 80, 181, 31))
        self.lineEdit_LightNo.setObjectName(_fromUtf8("lineEdit_LightNo"))
        self.Button_LightNo = QtGui.QPushButton(self.tab)
        self.Button_LightNo.setEnabled(True)
        self.Button_LightNo.setGeometry(QtCore.QRect(240, 80, 101, 31))
        self.Button_LightNo.setObjectName(_fromUtf8("Button_LightNo"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.pushButton_Export = QtGui.QPushButton(self.addressing)
        self.pushButton_Export.setGeometry(QtCore.QRect(650, 520, 131, 41))
        self.pushButton_Export.setObjectName(_fromUtf8("pushButton_Export"))
        self.label_fixture = QtGui.QLabel(self.addressing)
        self.label_fixture.setGeometry(QtCore.QRect(20, 319, 340, 240))
        self.label_fixture.setFrameShape(QtGui.QFrame.Box)
        self.label_fixture.setFrameShadow(QtGui.QFrame.Plain)
        self.label_fixture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fixture.setObjectName(_fromUtf8("label_fixture"))
        self.Clear = QtGui.QPushButton(self.addressing)
        self.Clear.setGeometry(QtCore.QRect(510, 520, 131, 41))
        self.Clear.setObjectName(_fromUtf8("Clear"))
        self.tabWidget.addTab(self.addressing, _fromUtf8(""))
        self.fixedcolor = QtGui.QWidget()
        self.fixedcolor.setObjectName(_fromUtf8("fixedcolor"))
        self.lineEdit_R = QtGui.QLineEdit(self.fixedcolor)
        self.lineEdit_R.setEnabled(False)
        self.lineEdit_R.setGeometry(QtCore.QRect(295, 350, 41, 20))
        self.lineEdit_R.setObjectName(_fromUtf8("lineEdit_R"))
        self.horizontalSlider_B = QtGui.QSlider(self.fixedcolor)
        self.horizontalSlider_B.setEnabled(False)
        self.horizontalSlider_B.setGeometry(QtCore.QRect(45, 410, 241, 19))
        self.horizontalSlider_B.setMaximum(255)
        self.horizontalSlider_B.setProperty("value", 255)
        self.horizontalSlider_B.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_B.setObjectName(_fromUtf8("horizontalSlider_B"))
        self.lineEdit_B = QtGui.QLineEdit(self.fixedcolor)
        self.lineEdit_B.setEnabled(False)
        self.lineEdit_B.setGeometry(QtCore.QRect(295, 410, 41, 20))
        self.lineEdit_B.setObjectName(_fromUtf8("lineEdit_B"))
        self.horizontalSlider_G = QtGui.QSlider(self.fixedcolor)
        self.horizontalSlider_G.setEnabled(False)
        self.horizontalSlider_G.setGeometry(QtCore.QRect(45, 380, 241, 19))
        self.horizontalSlider_G.setMaximum(255)
        self.horizontalSlider_G.setProperty("value", 255)
        self.horizontalSlider_G.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_G.setObjectName(_fromUtf8("horizontalSlider_G"))
        self.horizontalSlider_R = QtGui.QSlider(self.fixedcolor)
        self.horizontalSlider_R.setEnabled(False)
        self.horizontalSlider_R.setGeometry(QtCore.QRect(45, 350, 241, 19))
        self.horizontalSlider_R.setMaximum(255)
        self.horizontalSlider_R.setProperty("value", 255)
        self.horizontalSlider_R.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_R.setObjectName(_fromUtf8("horizontalSlider_R"))
        self.label_31 = QtGui.QLabel(self.fixedcolor)
        self.label_31.setGeometry(QtCore.QRect(15, 350, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.fixedcolor)
        self.label_32.setGeometry(QtCore.QRect(15, 380, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lineEdit_G = QtGui.QLineEdit(self.fixedcolor)
        self.lineEdit_G.setEnabled(False)
        self.lineEdit_G.setGeometry(QtCore.QRect(295, 380, 41, 20))
        self.lineEdit_G.setObjectName(_fromUtf8("lineEdit_G"))
        self.label_33 = QtGui.QLabel(self.fixedcolor)
        self.label_33.setGeometry(QtCore.QRect(15, 410, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.hueView = QtGui.QFrame(self.fixedcolor)
        self.hueView.setGeometry(QtCore.QRect(15, 20, 765, 257))
        self.hueView.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hueView.setMouseTracking(True)
        self.hueView.setStyleSheet(_fromUtf8("image: url(:/HueView/GAMUT.PNG);"))
        self.hueView.setFrameShape(QtGui.QFrame.Box)
        self.hueView.setFrameShadow(QtGui.QFrame.Plain)
        self.hueView.setLineWidth(1)
        self.hueView.setObjectName(_fromUtf8("hueView"))
        self.label_cursur = QtGui.QLabel(self.hueView)
        self.label_cursur.setGeometry(QtCore.QRect(0, 250, 8, 8))
        self.label_cursur.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"image: url(:/logo/CK.ico);\n"
""))
        self.label_cursur.setFrameShape(QtGui.QFrame.Box)
        self.label_cursur.setLineWidth(2)
        self.label_cursur.setText(_fromUtf8(""))
        self.label_cursur.setObjectName(_fromUtf8("label_cursur"))
        self.tabWidget.addTab(self.fixedcolor, _fromUtf8(""))
        self.colorwash = QtGui.QWidget()
        self.colorwash.setObjectName(_fromUtf8("colorwash"))
        self.label_2 = QtGui.QLabel(self.colorwash)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_washstop = QtGui.QPushButton(self.colorwash)
        self.pushButton_washstop.setGeometry(QtCore.QRect(670, 110, 101, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_washstop.sizePolicy().hasHeightForWidth())
        self.pushButton_washstop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_washstop.setFont(font)
        self.pushButton_washstop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_washstop.setAutoDefault(False)
        self.pushButton_washstop.setDefault(False)
        self.pushButton_washstop.setFlat(False)
        self.pushButton_washstop.setObjectName(_fromUtf8("pushButton_washstop"))
        self.frame_wash = QtGui.QFrame(self.colorwash)
        self.frame_wash.setGeometry(QtCore.QRect(10, 30, 771, 31))
        self.frame_wash.setStyleSheet(_fromUtf8(""))
        self.frame_wash.setFrameShape(QtGui.QFrame.Box)
        self.frame_wash.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_wash.setObjectName(_fromUtf8("frame_wash"))
        self.label_10 = QtGui.QLabel(self.colorwash)
        self.label_10.setGeometry(QtCore.QRect(600, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalSlider_2 = QtGui.QSlider(self.colorwash)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(110, 80, 471, 20))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(30)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_2.setTickInterval(0)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.label_6 = QtGui.QLabel(self.colorwash)
        self.label_6.setGeometry(QtCore.QRect(640, 80, 46, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_washstart = QtGui.QPushButton(self.colorwash)
        self.pushButton_washstart.setGeometry(QtCore.QRect(560, 110, 101, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_washstart.setFont(font)
        self.pushButton_washstart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_washstart.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_washstart.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_washstart.setAcceptDrops(False)
        self.pushButton_washstart.setAutoFillBackground(False)
        self.pushButton_washstart.setStyleSheet(_fromUtf8(""))
        self.pushButton_washstart.setAutoDefault(False)
        self.pushButton_washstart.setDefault(False)
        self.pushButton_washstart.setFlat(False)
        self.pushButton_washstart.setObjectName(_fromUtf8("pushButton_washstart"))
        self.tabWidget.addTab(self.colorwash, _fromUtf8(""))
        self.channeltest = QtGui.QWidget()
        self.channeltest.setObjectName(_fromUtf8("channeltest"))
        self.label_35 = QtGui.QLabel(self.channeltest)
        self.label_35.setGeometry(QtCore.QRect(20, 480, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalSlider_value = QtGui.QSlider(self.channeltest)
        self.horizontalSlider_value.setGeometry(QtCore.QRect(70, 480, 160, 21))
        self.horizontalSlider_value.setMaximum(255)
        self.horizontalSlider_value.setProperty("value", 255)
        self.horizontalSlider_value.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_value.setObjectName(_fromUtf8("horizontalSlider_value"))
        self.pushButton_testchannelAllOn = QtGui.QPushButton(self.channeltest)
        self.pushButton_testchannelAllOn.setGeometry(QtCore.QRect(644, 470, 131, 31))
        self.pushButton_testchannelAllOn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_testchannelAllOn.setDefault(False)
        self.pushButton_testchannelAllOn.setFlat(False)
        self.pushButton_testchannelAllOn.setObjectName(_fromUtf8("pushButton_testchannelAllOn"))
        self.tableWidget_channeltest = QtGui.QTableWidget(self.channeltest)
        self.tableWidget_channeltest.setEnabled(True)
        self.tableWidget_channeltest.setGeometry(QtCore.QRect(10, 20, 782, 421))
        self.tableWidget_channeltest.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_channeltest.setStyleSheet(_fromUtf8(""))
        self.tableWidget_channeltest.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_channeltest.setLineWidth(1)
        self.tableWidget_channeltest.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_channeltest.setDragDropOverwriteMode(False)
        self.tableWidget_channeltest.setShowGrid(True)
        self.tableWidget_channeltest.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_channeltest.setRowCount(32)
        self.tableWidget_channeltest.setColumnCount(16)
        self.tableWidget_channeltest.setObjectName(_fromUtf8("tableWidget_channeltest"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_channeltest.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_channeltest.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_channeltest.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(0, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_channeltest.setItem(31, 14, item)
        self.tableWidget_channeltest.horizontalHeader().setVisible(False)
        self.tableWidget_channeltest.horizontalHeader().setDefaultSectionSize(47)
        self.tableWidget_channeltest.horizontalHeader().setHighlightSections(True)
        self.tableWidget_channeltest.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_channeltest.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_channeltest.verticalHeader().setVisible(False)
        self.spinBox_2 = QtGui.QSpinBox(self.channeltest)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QtCore.QRect(240, 480, 42, 22))
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setProperty("value", 255)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.pushButton_testchannelAllOff = QtGui.QPushButton(self.channeltest)
        self.pushButton_testchannelAllOff.setGeometry(QtCore.QRect(500, 470, 131, 31))
        self.pushButton_testchannelAllOff.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_testchannelAllOff.setAutoDefault(False)
        self.pushButton_testchannelAllOff.setDefault(False)
        self.pushButton_testchannelAllOff.setFlat(False)
        self.pushButton_testchannelAllOff.setObjectName(_fromUtf8("pushButton_testchannelAllOff"))
        self.tabWidget.addTab(self.channeltest, _fromUtf8(""))
        self.DisconnectDeviceButton = QtGui.QPushButton(self.centralWidget)
        self.DisconnectDeviceButton.setEnabled(False)
        self.DisconnectDeviceButton.setGeometry(QtCore.QRect(140, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DisconnectDeviceButton.setFont(font)
        self.DisconnectDeviceButton.setObjectName(_fromUtf8("DisconnectDeviceButton"))
        self.label_Device_Status_2 = QtGui.QLabel(self.centralWidget)
        self.label_Device_Status_2.setGeometry(QtCore.QRect(620, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_Device_Status_2.setFont(font)
        self.label_Device_Status_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label_Device_Status_2.setFrameShape(QtGui.QFrame.Box)
        self.label_Device_Status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Device_Status_2.setObjectName(_fromUtf8("label_Device_Status_2"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(7, 40, 811, 20))
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_34 = QtGui.QLabel(self.centralWidget)
        self.label_34.setGeometry(QtCore.QRect(510, 680, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.commandLinkButton_info = QtGui.QCommandLinkButton(self.centralWidget)
        self.commandLinkButton_info.setGeometry(QtCore.QRect(10, 670, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        self.commandLinkButton_info.setFont(font)
        self.commandLinkButton_info.setIconSize(QtCore.QSize(15, 15))
        self.commandLinkButton_info.setCheckable(False)
        self.commandLinkButton_info.setAutoDefault(False)
        self.commandLinkButton_info.setDefault(False)
        self.commandLinkButton_info.setObjectName(_fromUtf8("commandLinkButton_info"))
        self.frame_7 = QtGui.QFrame(self.centralWidget)
        self.frame_7.setGeometry(QtCore.QRect(480, 680, 31, 21))
        self.frame_7.setStyleSheet(_fromUtf8("image: url(:/logo/CK.ico);"))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.commandLinkButton_help = QtGui.QCommandLinkButton(self.centralWidget)
        self.commandLinkButton_help.setGeometry(QtCore.QRect(80, 670, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        self.commandLinkButton_help.setFont(font)
        self.commandLinkButton_help.setIconSize(QtCore.QSize(15, 15))
        self.commandLinkButton_help.setCheckable(False)
        self.commandLinkButton_help.setAutoDefault(False)
        self.commandLinkButton_help.setDefault(False)
        self.commandLinkButton_help.setObjectName(_fromUtf8("commandLinkButton_help"))
        self.label_SJP = QtGui.QLabel(self.centralWidget)
        self.label_SJP.setGeometry(QtCore.QRect(540, 10, 31, 31))
        self.label_SJP.setText(_fromUtf8(""))
        self.label_SJP.setObjectName(_fromUtf8("label_SJP"))
        self.label_version = QtGui.QLabel(self.centralWidget)
        self.label_version.setGeometry(QtCore.QRect(390, 670, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_version.setFont(font)
        self.label_version.setObjectName(_fromUtf8("label_version"))
        self.label_operator = QtGui.QLabel(self.centralWidget)
        self.label_operator.setGeometry(QtCore.QRect(280, 15, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_operator.setFont(font)
        self.label_operator.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.label_operator.setObjectName(_fromUtf8("label_operator"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Vaya Manufacturing Tool", None))
        self.ConnectDeviceButton.setText(_translate("MainWindow", "Connect", None))
        self.label_Device_Status.setText(_translate("MainWindow", " Status:", None))
        self.pushButton_CH1.setText(_translate("MainWindow", "Channel 1", None))
        self.pushButton_CH2.setText(_translate("MainWindow", "Channel 2", None))
        self.pushButton_CH3.setText(_translate("MainWindow", "Channel 3", None))
        self.pushButton_CH4.setText(_translate("MainWindow", "Channel 4", None))
        self.pushButton_ALLON.setText(_translate("MainWindow", "ALL ON", None))
        self.pushButton_ALLOFF.setText(_translate("MainWindow", "ALL OFF", None))
        self.label_14.setText(_translate("MainWindow", " RS485 Reliability Test", None))
        self.label_15.setText(_translate("MainWindow", "Successful Transfer", None))
        self.label_16.setText(_translate("MainWindow", "Failed Transfer", None))
        self.pushButton_test.setText(_translate("MainWindow", "Start", None))
        self.pushButton_test_2.setText(_translate("MainWindow", "Stop", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:normal; color:#284664;\">DMX Test</span></p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#284664;\">Basic</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "ESTA Manufacturer ID for PHILIPS", None))
        self.label_9.setText(_translate("MainWindow", "Manufacturer Site ID", None))
        self.label_11.setText(_translate("MainWindow", "Select CM", None))
        self.lineEdit_3.setText(_translate("MainWindow", "5068", None))
        self.lineEdit_4.setText(_translate("MainWindow", "05", None))
        self.lineEdit_UID.setText(_translate("MainWindow", "5068:________", None))
        self.GenerateUID_2.setText(_translate("MainWindow", "Generate UID", None))
        self.label_12.setText(_translate("MainWindow", "UID", None))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ff0000;\">NOTE:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">&gt; The first UID of the day will be generated based on Factory ID and Date Code.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">&gt; Check the Date and Supply Factory</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">&gt; Connect </span><span style=\" font-size:8pt; font-weight:600; color:#ff0000;\">One</span><span style=\" font-size:8pt;\"> unit when using Configuration Tool</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#003d5a;\">Parameter</span></p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "Production Date", None))
        self.pushButton_SelectPP.setText(_translate("MainWindow", "Select Profile", None))
        self.pushButton_SetPara.setText(_translate("MainWindow", "Set Parameters", None))
        self.pushButton_GetPara.setText(_translate("MainWindow", "Get Parameters", None))
        self.label_19.setText(_translate("MainWindow", "Model Description", None))
        self.label_20.setText(_translate("MainWindow", "DMX Footprint", None))
        self.label_21.setText(_translate("MainWindow", "Sequence Number (1-511)", None))
        self.label_22.setText(_translate("MainWindow", "Fixture Model", None))
        self.Config_PP.setText(_translate("MainWindow", "Fixture Image Displays Here", None))
        self.label_37.setText(_translate("MainWindow", "UID", None))
        self.label_27.setText(_translate("MainWindow", "File Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration), _translate("MainWindow", "Configuration", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UID", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DMX", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fixture Type", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RDM Version", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Footprint", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Firmware Version", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Manufacture ID", None))
        item = self.tableWidget_DiscoverFixtures.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Device Label", None))
        self.pushButton_Discover.setText(_translate("MainWindow", "Discover", None))
        self.label_23.setText(_translate("MainWindow", "DMX Start Address", None))
        self.Button_DMXSet.setText(_translate("MainWindow", "Set", None))
        self.label_25.setText(_translate("MainWindow", "Device Label", None))
        self.Button_LabelSet.setText(_translate("MainWindow", "Set", None))
        self.label_24.setText(_translate("MainWindow", "Light Number", None))
        self.Button_LightNo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Light Number is only valid if ALL lights have exactly 3 Channels</p></body></html>", None))
        self.Button_LightNo.setText(_translate("MainWindow", "Set", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Basic Settings", None))
        self.pushButton_Export.setText(_translate("MainWindow", "Export Report", None))
        self.label_fixture.setText(_translate("MainWindow", "Fixture Display", None))
        self.Clear.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addressing), _translate("MainWindow", "Addressing", None))
        self.lineEdit_R.setText(_translate("MainWindow", "255", None))
        self.lineEdit_B.setText(_translate("MainWindow", "255", None))
        self.label_31.setText(_translate("MainWindow", "R", None))
        self.label_32.setText(_translate("MainWindow", "G", None))
        self.lineEdit_G.setText(_translate("MainWindow", "255", None))
        self.label_33.setText(_translate("MainWindow", "B", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fixedcolor), _translate("MainWindow", "Fixed Color", None))
        self.label_2.setText(_translate("MainWindow", "Color Cycle", None))
        self.pushButton_washstop.setText(_translate("MainWindow", "Stop", None))
        self.label_10.setText(_translate("MainWindow", "1 ", None))
        self.label_6.setText(_translate("MainWindow", "Second", None))
        self.pushButton_washstart.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colorwash), _translate("MainWindow", "Color Wash", None))
        self.label_35.setText(_translate("MainWindow", "Value", None))
        self.pushButton_testchannelAllOn.setText(_translate("MainWindow", "ALL ON", None))
        self.tableWidget_channeltest.setSortingEnabled(False)
        item = self.tableWidget_channeltest.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "14", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "15", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "16", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "17", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "18", None))
        item = self.tableWidget_channeltest.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "20", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "14", None))
        item = self.tableWidget_channeltest.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "16", None))
        __sortingEnabled = self.tableWidget_channeltest.isSortingEnabled()
        self.tableWidget_channeltest.setSortingEnabled(False)
        item = self.tableWidget_channeltest.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_channeltest.item(0, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_channeltest.item(0, 2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_channeltest.item(0, 3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_channeltest.item(0, 4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_channeltest.item(0, 5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_channeltest.item(0, 6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_channeltest.item(0, 7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_channeltest.item(0, 8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget_channeltest.item(0, 9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_channeltest.item(0, 10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget_channeltest.item(0, 11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget_channeltest.item(0, 12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget_channeltest.item(0, 13)
        item.setText(_translate("MainWindow", "14", None))
        item = self.tableWidget_channeltest.item(0, 14)
        item.setText(_translate("MainWindow", "15", None))
        item = self.tableWidget_channeltest.item(0, 15)
        item.setText(_translate("MainWindow", "16", None))
        item = self.tableWidget_channeltest.item(31, 14)
        item.setText(_translate("MainWindow", "512", None))
        self.tableWidget_channeltest.setSortingEnabled(__sortingEnabled)
        self.pushButton_testchannelAllOff.setText(_translate("MainWindow", "ALL OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.channeltest), _translate("MainWindow", "Channel Test", None))
        self.DisconnectDeviceButton.setText(_translate("MainWindow", "Disconnect", None))
        self.label_Device_Status_2.setText(_translate("MainWindow", "No Smart Jack Pro Connected", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4891d9;\">Philips Solid State Lighting Solutions</span></p></body></html>", None))
        self.commandLinkButton_info.setText(_translate("MainWindow", "Info", None))
        self.commandLinkButton_help.setText(_translate("MainWindow", "Help", None))
        self.label_version.setText(_translate("MainWindow", "Ver.: V1.0.3", None))
        self.label_operator.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Operator: </span></p></body></html>", None))

import gamut_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

